#
# URL settings
#
# these need to be adjusted depending on target platform,
# local Jekyll tests need different settings than github-pages :-(


# "real" deployment with github-pages but custom domain
# -----------------------------------------------------
url: https://faq.req42.de
imageurl: https://faq.req42.de
baseurl:
#######################################################




#
# basic settings
#
title: req42 FAQ
description: frequently asked questions on req42.
avatar: /assets/img/avatar.png
favicon: favicon.ico
language: en

#
# want disqus comments?
#
disqus: false


# Analytics
analytics: false

#
# Icons
#
icons:
  rss: false
  email: false
  github: false
  twitter: false
  google_plus: 
  stack_overflow: false

#
# Prettify url.
#
permalink: pretty


#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent answers
str_show_all_posts: Show all questions/answers

#
# Gems.
#
plugins:
#  - jekyll-paginate
  - jemoji
  - jekyll-github-metadata
  - jekyll-sitemap
  - jekyll-seo-tag
#
# Styles: see "_sass/base/_variables.scss"
#

#
# !! Danger zone !!
#

include: ["_pages", "robots.txt"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - Dockerfile
  - _manage-site.sh
  - _docker*
  - README.md
  - originals/

